# Generated by Django 6.0.7 on 2026-08-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_transacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='categoria',
        ),
        migrations.AddField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], default='despesa', max_length=7),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
